### ISSUE TITLE
installing exenstions with jupyter-nbextension

### ISSUE THREAD

**Issue by kain88-de** [ipython-contrib/IPython-notebook-extensions#253]
I'm trying to install some of the extensions in the new jupyter notebook.
I already figured out that the install command in the wiki only works from a checkout of this repository.

```bash
jupyter-nbextension install --user usability/codefolding
jupyter-nbextension enable codefolding
```

Installation is fine but I can't enable the extension.

```bash
/home/max/.local/lib/python2.7/site-packages/IPython/utils/path.py:258: UserWarning: get_ipython_dir has moved to the IPython.paths module
  warn("get_ipython_dir has moved to the IPython.paths module")
Traceback (most recent call last):
  File "/home/max/.local/bin/jupyter-nbextension", line 6, in <module>
    main()
  File "/home/max/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 261, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/max/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/home/max/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 401, in start
    super(NBExtensionApp, self).start()
  File "/home/max/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 250, in start
    self.subapp.start()
  File "/home/max/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 351, in start
    self.enable_nbextension(self.extra_args[0])
  File "/home/max/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 341, in enable_nbextension
    from notebook.services.config import ConfigManager
ImportError: No module named services.config
```

**Comment by juhasch** [comment]
To me it looks like your Jupyter notebook installation is not correct.
It is probably better to ask at https://github.com/jupyter/notebook , where one of the core developers might help you. This stuff is pretty new and it looks like you don't get to the point where the notebook extension itself is part of the problem you have.

**Comment by locojay** [comment]
having the same issue. installed the latest notebook version.

**Comment by juhasch** [comment]
Fixed by https://github.com/jupyter/notebook/pull/289
