### ISSUE TITLE
Error loading server extension nbextensions

### ISSUE THREAD

**Issue by shaharkadmiel** [ipython-contrib/IPython-notebook-extensions#304]
Hi, just upgraded to Jupyter 4.x so I had to reinstall all my nbextentions.

Tried doing python setup.py install after downloading `IPython-notebook-extensions-master`.
That worked fine but now everytime I load a notebook I get:

```python
[W 14:24:21.004 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/Users/Shahar/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/notebookapp.py", line 989, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/Shahar/Library/Jupyter/extensions/nbextensions.py", line 12, in <module>
        import yaml
    ImportError: No module named yaml
```

any ideas?

**Comment by juhasch** [comment]
It looks like you are missing the `yaml` package in your Python installation. Once you install this package everything should work.

**Comment by GCardellini** [comment]
I am experiencing the same problem:

```javascript 
(bw2_py2)giuseppec@giuseppec-Latitude-E6530 ~ $ ipython notebook --browser=chromium-browser --notebook-dir=/home/giuseppec/Dropbox/'FORMIT (3)'
[W 12:27:32.773 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/home/giuseppec/miniconda3/envs/bw2_py2/lib/python2.7/site-packages/notebook/notebookapp.py", line 991, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/giuseppec/miniconda3/envs/bw2_py2/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/giuseppec/.local/share/jupyter/extensions/nbextensions.py", line 12, in <module>
        import yaml
    ImportError: No module named yaml>
```

also in another conda enviro:

```javascript 
(bw2_py3)giuseppec@giuseppec-Latitude-E6530 ~ $ ipython notebook --browser=chromium-browser --notebook-dir=/home/giuseppec/Dropbox/'FORMIT (3)'
[W 12:34:57.974 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/home/giuseppec/miniconda3/envs/bw2_py3/lib/python3.4/site-packages/notebook/notebookapp.py", line 991, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/giuseppec/miniconda3/envs/bw2_py3/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/home/giuseppec/.local/share/jupyter/extensions/nbextensions.py", line 12, in <module>
        import yaml
    ImportError: No module named 'yaml'
```
even if in both I have yaml insttalled....but opening the notebook in the root environment I do not get this problem

Any Idea?

**Comment by juhasch** [comment]
Which environment is specified in your kernelspec file `kernel.json` ?
(Use `jupyter kernelspec list` to find where it is located)

**Comment by GCardellini** [comment]
Thanks...but really could not find this file...not even searching with 

```javascript 
sudo find / -iname 'kernel.json' 2>errors_2.txt
```

**Comment by juhasch** [comment]
What does the command `jupyter kernelspec list` say ?

**Comment by GCardellini** [comment]
in root enviro (the on working)
```
giuseppec@giuseppec-Latitude-E6530 ~ $ jupyter kernelspec list
Available kernels:
  python3
``` 
in the others...
``` 
(bw2_py2)giuseppec@giuseppec-Latitude-E6530 ~ $ jupyter kernelspec list
Available kernels:
  python2    /home/giuseppec/miniconda3/envs/bw2_py2/lib/python2.7/site-packages/ipykernel/resources

(bw2_py3)giuseppec@giuseppec-Latitude-E6530 ~ $ jupyter kernelspec list
Available kernels:
  python3
```

**Comment by GCardellini** [comment]
solved the problem. 
pyyaml must be installed instead of yaml (I installed pyyaml with conda and also worked)
(http://stackoverflow.com/questions/20966921/ansible-galaxy-throws-importerror-no-module-named-yaml)

**Comment by jcb91** [comment]
This should be fixed by #387

**Comment by focus-shift** [comment]
Hi,
      I just installed nbextensions today via setup.py. I ran into the same issue. I'm on Kubuntu 14.04. I solved the problem by running
```
sudo apt-get install python3-yaml
```
to install an appropriate yaml package. This wasn't much of a headache but it would be convenient if the setup.py could check that an appropriate yaml package is installed and crash if it can't find one. Altogether the extensions configuration page is great though!

**Comment by juhasch** [comment]
Closing as outdated.
