### ISSUE TITLE
Uncaught exception: RuntimeError: Cannot write() after finish()

### ISSUE THREAD

**Issue by JanSchulz** [ipython-contrib/IPython-notebook-extensions#319]
I just found multiple entries like this in the log of the notebook window.
```
[I 21:24:00.160 NotebookApp] 302 GET /nbextensions/config/rendermd/nbextensions/usability/codefolding/codefolding_firstline_unfolded.png (::1) 1.00ms
[E 21:24:00.162 NotebookApp] Uncaught exception GET /nbextensions/config/rendermd/nbextensions/usability/codefolding/codefolding_firstline_unfolded.png (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/nbextensions/config/rendermd/nbextensions/usability/codefolding/codefolding_firstline_unfolded.png', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Accept-Language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4', 'Referer': 'http://localhost:8888/nbextensions/config/rendermd/nbextensions/usability/codefolding/readme.md', 'Accept': 'image/webp,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "C:\portabel\miniconda\envs\ipython-notebook\lib\site-packages\tornado\web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\portabel\miniconda\envs\ipython-notebook\lib\site-packages\tornado\web.py", line 2721, in wrapper
        return method(self, *args, **kwargs)
      File "C:\Users\jschulz\AppData\Roaming\jupyter\extensions\nbextensions.py", line 100, in get
        page_title=path,
      File "C:\portabel\miniconda\envs\ipython-notebook\lib\site-packages\tornado\web.py", line 690, in write
        raise RuntimeError("Cannot write() after finish()")
    RuntimeError: Cannot write() after finish()
```

**Comment by flipphillips** [comment]
This is happening in Mac OS X also, tied to the python-markdown plug-in. Deactivating it stops this behavior. My simple test case is a notebook with

code: a = 42
md: {{a}}

Happy to upload it if necessary :)

```
[I 14:05:28.209 NotebookApp] 302 GET /nbextensions/config/rendermd/nbextensions/usability/python-markdown/python-markdown-post.png (::1) 0.39ms
[E 14:05:28.210 NotebookApp] Uncaught exception GET /nbextensions/config/rendermd/nbextensions/usability/python-markdown/python-markdown-post.png (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/nbextensions/config/rendermd/nbextensions/usability/python-markdown/python-markdown-post.png', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.5 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.5', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/nbextensions/config/rendermd/nbextensions/usability/python-markdown/readme.md'})
    Traceback (most recent call last):
      File "/Users/flip/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/flip/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2721, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/flip/Library/Jupyter/extensions/nbextensions.py", line 100, in get
        page_title=path,
      File "/Users/flip/anaconda/lib/python2.7/site-packages/tornado/web.py", line 690, in write
        raise RuntimeError("Cannot write() after finish()")
    RuntimeError: Cannot write() after finish()
```

**Comment by flipphillips** [comment]
Quick update here- downgrading tornado to 4.0.2 causes the problem to go away.

**Comment by juhasch** [comment]
I have never seen this.
@JanSchulz : What is your ZMQ version ?

**Comment by JanSchulz** [comment]
@juhasch `conda env export` reports this: `- pyzmq=14.6.0=py27_0`

**Comment by JanSchulz** [comment]
@juhasch `conda env export`reports the following:

* The kernel has `pyzmq=14.6.0=py27_0` and `tornado=4.2=py27_0`
* the notebook runs on `pyzmq=14.7.0=py34_0` and  `tornado=4.2.1=py34_0`

Not sure if that has anything to do with it, but the the server is running a up to date jupyter environment on py3.4 and the kernel is still on IPython 3.1

**Comment by juhasch** [comment]
Can you try if PR #322 fixes this ?

**Comment by shrijayan** [comment]
What is the solution for this still I get this issue?

```
[W 2024-02-27 05:11:46.726 ServerApp] 404 GET /api/contents/Projects/embedding-model-training/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py?content=0&hash=0&1709010706648 (IP_ADDRESS) 1.51ms referer=http://SERVER_ADDRESS/lab/workspaces/auto-R/tree/Projects/embedding-model-training/src/Dense_Retrieval_Fine_Tuning.ipynb
[I 2024-02-27 05:11:46.727 ServerApp] Refusing to serve hidden file or directory '/home/karrtik/Projects/embedding-model-training/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py', via 404 Error
[E 2024-02-27 05:11:46.727 ServerApp] Uncaught exception GET /api/contents/Projects/embedding-model-training/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py?content=0&hash=0&1709010706648 (IP_ADDRESS)
    HTTPServerRequest(protocol='http', host='SERVER_ADDRESS', method='GET', uri='/api/contents/Projects/embedding-model-training/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py?content=0&hash=0&1709010706648', version='HTTP/1.1', remote_ip='IP_ADDRESS')
    Traceback (most recent call last):
      ...
      ...
      ...
    RuntimeError: Cannot write() after finish()

```

**Comment by mfouesneau** [comment]
same issue here
