### ISSUE TITLE
extension for windows

### ISSUE THREAD

**Issue by SilasK** [ipython-contrib/IPython-notebook-extensions#385]
Hey 
It seems very promising what you do. 
Is it also available for windows? 
I tried to install using Anaconda but it didn't find a Windows version. 
Kind regards Silas

**Comment by jcb91** [comment]
As far as I know, there isn't anything OS-specific that should stop it working. Did you try the `python setup.py install`?

When you say
> it didn't find a Windows version
do you mean Anaconda was somehow looking for a windows-specific package?

**Comment by jcb91** [comment]
On closer investigation, this may be related to/fixed by #387

**Comment by SilasK** [comment]
Ok, I changed the yaml to pyyaml as indicated in #387. I was able to build the conda package. But now what do Ihave to do to install them finally?

**Comment by jcb91** [comment]
I'm not sure I understand your question - do you mean to activate and use a
given extension? You can activate and configure extensions from the page at
the notebook URL `/nbexrensions`?

**Comment by juhasch** [comment]
You can go to `c:\anaconda\conda-bld\win-64` and do a `conda install --file nbextensions-master-py34_0.tar.bz2`

**Comment by SilasK** [comment]
Hello,

I changed the yaml to pyyaml as indicated in #387

Then I build the conda package by running “conda build IPython-notebook-extensions” in the parent directory

In the readme is written:

then doing a “conda install nbextensions”



which didn’t worked for me. Conda says there is no win64 package of nbextension.



I can not yet configure extensions from the /extension site.



Kind regards

**Comment by SilasK** [comment]
Thank you I already advanced. But I got the following error message.



Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 337, in install
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 407, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 335, in add_defaults_to_specs
    if r.explicit(specs):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 871, in explicit
    if spec != 'conda']
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 313, in __init__
    self.vspecs = [VersionSpec(s) for s in parts[1].split('|')]
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 298, in __init__
    self.constraints = [VersionSpecAtom(vs) for vs in spec.split(',')]
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 286, in __init__
    self.regex = re.compile(rx)
  File "C:\Anaconda\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Anaconda\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

**Comment by juhasch** [comment]
Take a look ad #345. Hope this helps you.

**Comment by SilasK** [comment]
Thank you it worked
