### ISSUE TITLE
Server Extensions error

### ISSUE THREAD

**Issue by diego898** [ipython-contrib/IPython-notebook-extensions#494]
Hello,

Im not sure if this is related to #487, but after performing those fixes, which indeed did fix my codefoling extension and eliminated errors from my chrome developer console, I have the following after I type `jupyter notebook` in a terminal: 
```
[W 15:58:08.421 NotebookApp] Error loading server extension highlight_html_cfg
    Traceback (most recent call last):
      File "/Users/diego/anaconda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1005, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/diego/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/diego/Library/Jupyter/extensions/highlight_html_cfg.py", line 7, in <module>
        c = get_config()
    NameError: name 'get_config' is not defined
[W 15:58:08.477 NotebookApp] Error loading server extension ipy-aspell-server
    Traceback (most recent call last):
      File "/Users/diego/anaconda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1005, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/diego/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 658, in exec_module
      File "<frozen importlib._bootstrap_external>", line 764, in get_code
      File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/diego/Library/Jupyter/extensions/ipy-aspell-server.py", line 40
        print "open socket"
                          ^
    SyntaxError: Missing parentheses in call to 'print'
[W 15:58:08.483 NotebookApp] Error loading server extension highlight_latex_cfg
    Traceback (most recent call last):
      File "/Users/diego/anaconda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1005, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/diego/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/diego/Library/Jupyter/extensions/highlight_latex_cfg.py", line 7, in <module>
        c = get_config()
    NameError: name 'get_config' is not defined
```

**Comment by jcb91** [comment]
This is a duplicate of #490, and isn't related to #487. Essentially, #476 was a bit over-zealous in including all .py files in the extensions folder, as `ipy-aspell-server.py` is currently incompatible with python 3 (see #491 for a fix) and `highlight_latex_cfg.py` isn't a server extension at all, so shouldn't be loaded as one.

**Comment by diego898** [comment]
Hm. I went ahead and made the changes in #491 in my local repo, and reran `python setup.py install` but am still getting that part of the error. Frankly Im a bit confused where and how the extensions are in fact installed. 

One strange thing I noticed after fixing #487 is my ToC stopped regenerating automatically. I now have to toggle it on/off. 

* Where/how can I actually make the changes described in #491 
* How can I "update" my extensions so that they track this repo? I thought I was doing that but apparently I'm not.

**Comment by jcb91** [comment]
I'm afraid this is all a bit cobbled together at the moment, as you're rapidly discovering :wink: 
I'm afraid I didn't look at #491 carefully enough, and it actually applies the correct fixes, but to the wrong file - see my comment there for information on that.

I'm not sure about the toc regeneration problem - maybe open another issue for that?

I think the process you describe (make changes in a local repo, run `python setup.py install`) should be enough to update everything fine. You can track this repo by just doing `git pull` (assuming you're using `git`? Otherwise, I guess you could just delete your old copy and re-download the new repo source). Note however, that #491 is currently a pull request which hasn't been merged into the repo master branch yet, so you'd need to apply the changes separately.

I think on this occasion you've just run into some mess where we have two independent copies of the same file, which we shouldn't have, and is (understandably) confusing people...

**Comment by diego898** [comment]
thank you! this fixed it for me
